/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AM;

import com.mysql.cj.xdevapi.Statement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author karan
 */
public class Preferences extends javax.swing.JFrame {

    /**
     * Creates new form Preferences
     */
    int user_id = global.user_id;
    int flag = 0;

    public Preferences() {
        initComponents();
    }
public int getRandom(int min, int max) {
    Random random = new Random();
    return random.nextInt(max - min) + min;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Budget_cb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        EatingPref_cb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        typeoftravel_cb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        AccomodationPref_cb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Cuisine_cb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Drinker_cb = new javax.swing.JComboBox<>();
        personality_cb = new javax.swing.JComboBox<>();
        savepref = new javax.swing.JButton();
        question_cb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("PREFERENCES");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("If you are a group, then set preferences that");

        jLabel3.setText("Budget");

        Budget_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "High", "Medium", "Low", " " }));
        Budget_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Budget_cbActionPerformed(evt);
            }
        });

        jLabel4.setText("Eating Preferences");

        EatingPref_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Veg", "Non-Veg", "Vegan" }));
        EatingPref_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EatingPref_cbActionPerformed(evt);
            }
        });

        jLabel5.setText("Type of Travel");

        typeoftravel_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Leisure", "Tourist", "Adventure" }));
        typeoftravel_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeoftravel_cbActionPerformed(evt);
            }
        });

        jLabel6.setText("Accomodation Preference");

        AccomodationPref_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Apartment", "Bunglow", "Hotel", " ", " " }));

        jLabel7.setText("Cuisine");

        Cuisine_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Chinese", "Continental", "Indian", "Italian", " " }));

        jLabel8.setText("Drinker");

        jLabel10.setText("Personality Type");

        jLabel11.setText("What would be your go-to activity");

        Drinker_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Non Drinker", "Social Drinker" }));

        personality_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Introvert", "Extrovert", "Ambivert" }));
        personality_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personality_cbActionPerformed(evt);
            }
        });

        savepref.setText("Save Preferences");
        savepref.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveprefMouseClicked(evt);
            }
        });
        savepref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveprefActionPerformed(evt);
            }
        });

        question_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Preference", "Natural beauty", "Mega structures", "Historical places", "Heritage Tour", " " }));
        question_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question_cbActionPerformed(evt);
            }
        });

        jLabel9.setText("represent the majority of the group");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(savepref)
                .addGap(456, 456, 456))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Budget_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EatingPref_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeoftravel_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AccomodationPref_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(personality_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Drinker_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cuisine_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(question_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Budget_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addComponent(Cuisine_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(EatingPref_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Drinker_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typeoftravel_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(personality_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(AccomodationPref_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(question_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(savepref)
                .addGap(181, 181, 181))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Budget_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Budget_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Budget_cbActionPerformed

    private void EatingPref_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EatingPref_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EatingPref_cbActionPerformed

    private void typeoftravel_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeoftravel_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeoftravel_cbActionPerformed

    private void saveprefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveprefActionPerformed
        flag = 0;
        if (("Select Preference".equals((String)Budget_cb.getSelectedItem())) && flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            Budget_cb.requestFocus();
            flag = 1;
        }

        if (("Select Preference".equals((String)AccomodationPref_cb.getSelectedItem())) && flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            flag = 1;
        }
        if (("Select Preference".equals((String)Drinker_cb.getSelectedItem()))&& flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            flag = 1;
        }
        if (("Select Preference".equals((String)Cuisine_cb.getSelectedItem()))&& flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            flag = 1;
        }
        if (("Select Preference".equals((String)EatingPref_cb.getSelectedItem())) && flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            EatingPref_cb.requestFocus();
            flag = 1;
        }
        if (("Select Preference".equals((String)personality_cb.getSelectedItem()))&& flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            flag = 1;
        }
        if (("Select Preference".equals((String)question_cb.getSelectedItem()))&& flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            flag = 1;
        }
        if (("Select Preference".equals((String)typeoftravel_cb.getSelectedItem()))&& flag == 0) {
            JOptionPane.showMessageDialog(this, "All Field is required");
            flag = 1;
        }
        if(flag == 0){    
    java.sql.PreparedStatement pst= null;
    java.sql.Statement st=null;
    java.sql.ResultSet rs=null;
    java.sql.Connection con=null;
    
    
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/travelalong","root","iwontellthat1");
            Integer rnd = getRandom(0,1000000);
            String rnds = rnd.toString();
            //int ok= 11;
            pst=con.prepareStatement("INSERT INTO travelalong.preferences (`Budget`, `eating_pref`, `Travel_activities`, `User_ID`,`AccomodationPref`, `Cuisine`,`Drinker`,`personality_type`,`question`) VALUES (?,?,?,?,?,?,?,?,?);");
            pst.setString(1, (String) Budget_cb.getSelectedItem());
            pst.setString(2, (String) EatingPref_cb.getSelectedItem());
            pst.setString(3, (String) typeoftravel_cb.getSelectedItem());
            pst.setString(5, (String) AccomodationPref_cb.getSelectedItem());
            pst.setString(6, (String) Cuisine_cb.getSelectedItem());
            pst.setString(7, (String) Drinker_cb.getSelectedItem());
            pst.setString(8, (String) personality_cb.getSelectedItem());
            pst.setString(9, (String) question_cb.getSelectedItem());
            //pst.setInt(1, rnd);
            pst.setInt(4, this.user_id);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Preferences Updated!");
        }   catch (ClassNotFoundException ex) {
                Logger.getLogger(Preferences.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Preferences.class.getName()).log(Level.SEVERE, null, ex);
            }
          /*catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this, "Not working");
        }*/
      
        }
    }//GEN-LAST:event_saveprefActionPerformed

    private void saveprefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveprefMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_saveprefMouseClicked

    private void personality_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personality_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personality_cbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void question_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_question_cbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preferences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preferences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AccomodationPref_cb;
    private javax.swing.JComboBox<String> Budget_cb;
    private javax.swing.JComboBox<String> Cuisine_cb;
    private javax.swing.JComboBox<String> Drinker_cb;
    private javax.swing.JComboBox<String> EatingPref_cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> personality_cb;
    private javax.swing.JComboBox<String> question_cb;
    private javax.swing.JButton savepref;
    private javax.swing.JComboBox<String> typeoftravel_cb;
    // End of variables declaration//GEN-END:variables
}
